module.exports = [
   {
    category: 'Science',
    text: "¿Cuál es el elemento químico con el símbolo 'O'?",
    options: ["Oxígeno", "Oro", "Osmio", "Óxido"],
    answer: 0,
  },
  {
    category: 'Science',
    text: "¿Qué planeta es conocido como el 'Planeta Rojo'?",
    options: ["Marte", "Venus", "Júpiter", "Saturno"],
    answer: 0,
  },
  {
    category: 'Science',
    text: "¿Cómo se llama el proceso por el cual las plantas convierten la luz solar en energía?",
    options: ["Fotosíntesis", "Respiración", "Digestión", "Metabolismo"],
    answer: 0,
  },
  {
    category: 'Science',
    text: "¿En qué año ocurrió la Revolución Francesa?",
    options: ["1789", "1492", "1815", "1914"],
    answer: 0,
  },
  {
    category: 'History',
    text: "¿Quién fue el primer presidente de los Estados Unidos?",
    options: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"],
    answer: 1,
  },
  {
    category: 'History',
    text: "¿Qué imperio construyó el Coliseo en Roma?",
    options: ["Egipcio", "Griego", "Romano", "Bizantino"],
    answer: 2,
  },
  {
    category: 'Geography',
    text: "¿Cuál es el río más largo del mundo?",
    options: ["Nilo", "Amazonas", "Yangtsé", "Mississippi"],
    answer: 1,
  },
  {
    category: 'Geography',
    text: "¿Cuál es el país más grande del mundo en términos de área?",
    options: ["Estados Unidos", "China", "Rusia", "Canadá"],
    answer: 2,
  },
  {
    category: 'Geography',
    text: "¿Cuál es la capital de Japón?",
    options: ["Seúl", "Pekín", "Tokio", "Bangkok"],
    answer: 2,
  },
  {
    category: 'Entertainment',
    text: "¿Qué actor interpretó a Iron Man en el Universo Cinematográfico de Marvel?",
    options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"],
    answer: 1,
  },
  {
    category: 'Entertainment',
    text: "¿Cuál es la película más taquillera de la historia (hasta 2024)?",
    options: ["Avatar", "Titanic", "Avengers: Endgame", "El Rey León"],
    answer: 0,
  },
  {
    category: 'Entertainment',
    text: "¿Qué serie de televisión incluye a los personajes de Walter White y Jesse Pinkman?",
    options: ["Breaking Bad", "The Wire", "Mad Men", "Stranger Things"],
    answer: 0,
  },
  {
    category: 'Sports',
    text: "¿En qué deporte se utiliza un aro y una pelota como elementos principales?",
    options: ["Fútbol", "Baloncesto", "Tenis", "Voleibol"],
    answer: 1,
  },
  {
    category: 'Sports',
    text: "¿Qué país ha ganado más Copas del Mundo de Fútbol?",
    options: ["Alemania", "Italia", "Argentina", "Brasil"],
    answer: 3,
  },
  {
    category: 'Sports',
    text: "¿En qué ciudad se celebraron los Juegos Olímpicos de 2008?",
    options: ["Londres", "Atenas", "Pekín", "Sídney"],
    answer: 2,
  },
  {
    category: 'Technology',
    text: "¿Qué significa 'HTML'?",
    options: ["HyperText Markup Language", "High Transfer Machine Language", "Hyper Transfer Mode Logic", "Hidden Text Machine Language"],
    answer: 0,
  },
  {
    category: 'Technology',
    text: "¿Qué empresa desarrolló el sistema operativo Android?",
    options: ["Apple", "Google", "Microsoft", "Samsung"],
    answer: 1,
  },
  {
    category: 'Technology',
    text: "¿Qué se utiliza para almacenar datos en una base de datos relacional?",
    options: ["Archivos", "Tablas", "Gráficos", "Funciones"],
    answer: 1,
  },
];
